#!/bin/bash

if [ "${wizard_remove_data}" = "delete" ]; then
    rm -rf "${TRIM_PKGVAR:?}/config" "${TRIM_PKGVAR:?}/logs"
    rm -rf "/var/apps/${TRIM_APPNAME}/shares/icloud/photos" \
           "/var/apps/${TRIM_APPNAME}/shares/icloud/videos" \
           "/var/apps/${TRIM_APPNAME}/shares/icloud/notes"
fi

exit 0
