#!/bin/bash

if [ "${wizard_remove_data}" = "delete" ]; then
    SHARE_ROOT="/var/apps/${TRIM_APPNAME}/shares/icloud"
    rm -rf "${TRIM_PKGVAR:?}/config" "${TRIM_PKGVAR:?}/logs"
    rm -rf "${SHARE_ROOT}"
fi

exit 0
